language: rust
cache: cargo

git:
  depth: 3

rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
    - rust: beta

script:
  - make clean
  - make build
  - make test
