language: rust
cache: cargo

git:
  depth: 3

matrix:
  fast_finish: true
  include:
    - rust: nightly
      env: FEATURES="--no-default-features --features nightly"
    - rust: beta
    - rust: stable
  allow_failures:
    - rust: nightly

script:
  - cargo clean
  - cargo build --verbose $FEATURES
  - cargo test --verbose $FEATURES
